language: node_js
node_js:
  "node"
  "6"
  "5"
  "4"

before_deploy: "echo 'ready?'"
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
after_deploy: "echo 'Finished!'"